### ISSUE TITLE
output completely black

### ISSUE THREAD

**Issue by pranshu97** [andrewdcampbell/seam-carving#2]
The object removal goes fine during the visualization, the object gets removed. But during seam insertion, it turns fully black. The output image also is all black.

**Comment by pranshu97** [comment]
@andrewdcampbell I do get an output if I comment the "add_seam" inside the seam_insertion function(obviously smaller sized as seam are not inserted). Looks like there's something wrong with the add_seam function.

**Comment by Dev2022** [comment]
Hi pranshu, which numba are you using? Did u get any error for numba.
Thanks

**Comment by pranshu97** [comment]
I didn't get any error for numba. I just removed the "@jit" above the addseam() function and it worked.
